name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          git config core.autocrlf
          git config --global core.autocrlf || true
          git clone https://github.com/ocaml/opam-repository.git D:\opam-repo
          git -C D:\opam-repo checkout -b sunset ce6f3a1937eb3be

      - name: Set-up OCaml
#        uses: dra27/setup-ocaml@38e5927a2226c5c763f05124b643efa7f5fd1c15
        uses: dra27/setup-ocaml@38e5927a2226c5c763f05124b643efa7f5fd1c15
        with:
          ocaml-compiler: 4.14.0
          opam-repositories: |
            opam-repository-mingw: https://github.com/dra27/opam-repository-mingw.git#sunset
            default: D:/opam-repo#sunset

      - run: |
          git config core.autocrlf
          git config --global core.autocrlf || true

      - run: |
          opam list
          opam repo
          opam exec -- ocamlopt -config

      - run: |
          git -C D:\opam-repo merge origin/master
          opam exec -- md5sum D:/opam-repo/packages/ocaml-config/ocaml-config.3/files/gen_ocaml_config.ml.in
          opam update
          opam exec -- md5sum D:/.opam/repo/default/packages/ocaml-config/ocaml-config.3/files/gen_ocaml_config.ml.in
          git -C D:\.opam\repo\default config -l
          opam upgrade ocaml-config --unlock-base
          opam switch create foo --packages ocaml-variants.4.14.0+mingw64c
