name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.14.x
          - ocaml-variants.4.14.1+mingw32c
          - ocaml-variants.4.14.1+flambda+mingw32c
          - ocaml-variants.4.14.1+mingw64c
          - ocaml-variants.4.14.1+flambda+mingw64c
          - ocaml-variants.4.14.1+msvc32c
          - ocaml-variants.4.14.1+msvc64c

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up OCaml
        uses: dra27/setup-ocaml@4.14.1
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            opam-repository-mingw: https://github.com/dra27/opam-repository-mingw.git#sunset
            default: https://github.com/ocaml/opam-repository.git

      - run: |
          opam list
          opam exec -- ocamlopt -config
